clear
tercih=0; %choice forframe is zero if rotating frame, 1 if lab frame
transverse=1;
h0 = figure('Units','points', ...
	'Color',[1 1 1], ...
	'Name','EE 519 TERM PROJECT                                                                                                                                                  Yoldas Ataseven', ...
	'NumberTitle','off', ...
	'Position',[15.75 14.35 741 535.5], ...
    'Pointer','arrow',...
	'Resize','off', ...
	'Tag','Fig1');
sim = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','close all', ...
   'ListboxTop',0, ...
	'Callback','set(txtexplain,''Visible'',''off'');sim1', ...
	'Position',[92.25 34.75 79.5 26.25], ...
	'String','Simulate!', ...
	'Tag','Pushbutton1');
kapat = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','close all', ...
	'ListboxTop',0, ...
	'Position',[602.25 34.75 79.5 26.25], ...
	'String','Close', ...
	'Tag','Pushbutton1');
kapat2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','close,giris', ...
	'ListboxTop',0, ...
	'Position',[402.25 34.75 79.5 26.25], ...
	'String','Defaults', ...
	'Tag','Pushbutton1');
txtsus = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.95 0.95 1], ...
	'ListboxTop',0, ...
	'Position',[1 206.25 101.5 19.5], ...
	'String',' ', ...
	'Style','text', ...
	'Tag','StaticText1');
but_rotating = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.95 0.95 1], ...
	'ListboxTop',0, ...
	'Position',[102.5 206.25 100 19.5], ...
   'Callback','set(but_lab,''Value'',0);tercih=0;', ...
   	'String','Rotating Frame', ...
   'Style','radiobutton', ...
   'Value',1,...
	'Tag','Radiobutton1');
but_lab = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.95 0.95 1], ...
	'ListboxTop',0, ...
   'Position',[202.5 206.25 200 19.5], ...
   'Callback','set(but_rotating,''Value'',0);tercih=1;', ...
	'String','Laboratory Frame', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton1');
but_3d = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.95 0.95 1], ...
	'ListboxTop',0, ...
	'Position',[402.5 206.25 100 19.5], ...
   'Callback','set(but_trans,''Value'',0);transverse=0;', ...
   	'String','3-D view', ...
   'Style','radiobutton', ...
   	'Tag','Radiobutton1');
but_trans = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.95 0.95 1], ...
	'ListboxTop',0, ...
   'Position',[502.5 206.25 300 19.5], ...
   'Callback','set(but_3d,''Value'',0);transverse=1;', ...
	'String','Transverse view', ...
	'Style','radiobutton', ...
    'Value',1,...
	'Tag','Radiobutton1');
txtexplain = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[206.25 377.25 341.25 13.5], ...
	'String','NMR SIMULATOR', ...
	'Style','text', ...
	'Tag','StaticText1');
txtexplain2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[216.25 357.25 341.25 103.5], ...
	'String','The default values will simulate an pi/2 pulse on-resonance excitation. N is the number of voxels in each dimension. For off-resonance excitation, change any of Bo,w,Gyromagnetic constant or ''Slice to view'' values.The initial magnetization vector is for rotating frame', ...
	'Style','text', ...
	'Tag','StaticText1');
%-----------------------------------Gx1-------------------------------------
%Gxapp1
txtGxapp1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[46.25 372.25 41.25 33.5], ...
	'String','Gx application time (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGxapp1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[46.5 355.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gxapp1
%Gxamp1
txtGxamp1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[36.25 252.25 61.25 33.5], ...
	'String','Gx amplitude (micro Tesla):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGxamp1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[46.5 245.25 38.25 16.5], ...
	'String','-1', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gxamp1
%Gxdur1
txtGxdur1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[46.25 307.25 41.25 33.5], ...
	'String','Gx duration (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGxdur1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[46.5 300.25 38.25 16.5], ...
	'String','50', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gxdur1
%-----------------------------------Gx2-------------------------------------
%Gxapp2
txtGxapp2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[106.25 372.25 41.25 33.5], ...
	'String','Gx application time (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGxapp2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[106.5 355.25 38.25 16.5], ...
	'String','50', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gxapp2
%Gxamp2
txtGxamp2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[96.25 252.25 61.25 33.5], ...
	'String','Gx amplitude (micro Tesla):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGxamp2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[106.5 245.25 38.25 16.5], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gxamp2
%Gxdur2
txtGxdur2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[106.25 307.25 41.25 33.5], ...
	'String','Gx duration (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGxdur2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[106.5 300.25 38.25 16.5], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gxdur2

%-----------------------------------Gx3-------------------------------------
%Gxapp3
txtGxapp3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[166.25 372.25 41.25 33.5], ...
	'String','Gx application time (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGxapp3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[166.5 355.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gxapp3
%Gxamp3
txtGxamp3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[156.25 252.25 61.25 33.5], ...
	'String','Gx amplitude (micro Tesla):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGxamp3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[166.5 245.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gxamp3
%Gxdur3
txtGxdur3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[166.25 307.25 41.25 33.5], ...
	'String','Gx duration (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGxdur3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[166.5 300.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gxdur3

%-----------------------------------Gx4-------------------------------------
%Gxapp4
txtGxapp4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[226.25 372.25 41.25 33.5], ...
	'String','Gx application time (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGxapp4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[226.5 355.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gxapp4
%Gxamp4
txtGxamp4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[216.25 252.25 61.25 33.5], ...
	'String','Gx amplitude (micro Tesla):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGxamp4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[226.5 245.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gxamp4
%Gxdur4
txtGxdur4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[226.25 307.25 41.25 33.5], ...
	'String','Gx duration (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGxdur4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[226.5 300.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gxdur4
%-----------------------------------Gy1-------------------------------------
%Gyapp1
txtGyapp1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[346.25 372.25 41.25 33.5], ...
	'String','Gy application time (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGyapp1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[346.5 355.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gyapp1
%Gyamp1
txtGyamp1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[336.25 252.25 61.25 33.5], ...
	'String','Gy amplitude (micro Tesla):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGyamp1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[346.5 245.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gyamp1
%Gydur1
txtGydur1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[346.25 307.25 41.25 33.5], ...
	'String','Gy duration (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGydur1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[346.5 300.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gydur1
%-----------------------------------Gy2-------------------------------------
%Gyapp2
txtGyxapp2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[406.25 372.25 41.25 33.5], ...
	'String','Gy application time (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGyapp2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[406.5 355.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gyapp2
%Gyamp2
txtGyamp2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[396.25 252.25 61.25 33.5], ...
	'String','Gy amplitude (micro Tesla):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGyamp2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[406.5 245.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gyamp2
%Gydur2
txtGydur2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[406.25 307.25 41.25 33.5], ...
	'String','Gy duration (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGydur2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[406.5 300.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gydur2

%-----------------------------------Gy3-------------------------------------
%Gyapp3
txtGyapp3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[466.25 372.25 41.25 33.5], ...
	'String','Gy application time (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGyapp3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[466.5 355.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gyapp3
%Gyamp3
txtGyamp3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[456.25 252.25 61.25 33.5], ...
	'String','Gy amplitude (micro Tesla):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGyamp3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[466.5 245.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gyamp3
%Gydur3
txtGydur3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[466.25 307.25 41.25 33.5], ...
	'String','Gy duration (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGydur3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[466.5 300.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gydur3

%-----------------------------------Gy4-------------------------------------
%Gyapp4
txtGyapp4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[526.25 372.25 41.25 33.5], ...
	'String','Gy application time (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGyapp4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[526.5 355.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gyapp4
%Gyamp4
txtGyamp4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[516.25 252.25 61.25 33.5], ...
	'String','Gy amplitude (micro Tesla):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGyamp4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[526.5 245.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gyamp4
%Gydur4
txtGydur4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[526.25 307.25 41.25 33.5], ...
	'String','Gy duration (ms):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGydur4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[526.5 300.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gydur4
%-----------------------------------Gz-------------------------------------
%Gyampz
txtGzamp = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[636.25 252.25 61.25 33.5], ...
	'String','Gz amplitude (micro Tesla):', ...
	'Style','text', ...
	'Tag','StaticText1');
editGzamp = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[646.5 245.25 38.25 16.5], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Gzamp

%---------------------------------------N----------------------------------
%N
txtN = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[545.25 150.25 41.25 33.5], ...
	'String','N:', ...
	'Style','text', ...
	'Tag','StaticText1');
editN = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[546.5 155.25 38.25 16.5], ...
	'String','14', ...
	'Style','edit', ...
	'Tag','EditText1');
% end N
%---------------------------------slice to view----------------------------------
%viewed slice
txtslice = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[637.25 162.25 41.25 33.5], ...
	'String','Slice to view:', ...
	'Style','text', ...
	'Tag','StaticText1');
editslice = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[640.5 155.25 38.25 16.5], ...
	'String','7', ...
	'Style','edit', ...
	'Tag','EditText1');
% end viewed slice

%---------------------------------slice thickness----------------------------------
% slice thickness
txtthickness = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[630.25 112.25 56.25 33.5], ...
	'String','Slice thickness(mm):', ...
	'Style','text', ...
	'Tag','StaticText1');
editthickness = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[640.5 105.25 38.25 16.5], ...
	'String','0.5', ...
	'Style','edit', ...
	'Tag','EditText1');
% end slice thickness

%--------------------------------------------------------M(0-)--------------------------------
%Mx
txtMx = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[46.25 172.25 41.25 13.5], ...
	'String','Mx''(0-)', ...
	'Style','text', ...
	'Tag','StaticText1');
editMx = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[46.5 155.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Mx

% My
txtMy = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[46.25 134.5 41.25 10.5], ...
	'String','My''(0-)', ...
	'Style','text', ...
	'Tag','StaticText1');
editMy = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	   'Enable','on',...
	'ListboxTop',0, ...
	'Position',[46.5 115 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end My

% Mz
editMz = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
		'ListboxTop',0, ...
	'Position',[46.25 75.75 38.25 16.5], ...
   'String','3', ...
   'Enable','on',...
	'Style','edit', ...
	'Tag','EditText1');
txtMz = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[35.25 95.5 61.25 10.5], ...
	'String','Mz''(0-)', ...
   'Enable','on',...
	'Style','text', ...
	'Tag','StaticText1');
% end Mz
%-------------------------------------Bo-------------------------------------
%Bo
txtBo = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[146.25 172.25 41.25 13.5], ...
	'String','Bo (Tesla)', ...
	'Style','text', ...
	'Tag','StaticText1');
editBo = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[146.5 155.25 38.25 16.5], ...
	'String','3', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Bo
%---------------------------Gyromagnetic Constant----------------------------
txtgamma = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[125.25 117.25 81.25 23.5], ...
	'String','Gyromagnetic Constant (MHz/T)', ...
	'Style','text', ...
	'Tag','StaticText1');
editgamma = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[146.5 100.25 38.25 16.5], ...
	'String','42.58', ...
	'Style','edit', ...
	'Tag','EditText1');
%--------------------------------------RF Field----------------------------------
%B1
txtB1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[230.25 172.25 71.25 13.5], ...
	'String','B1 (microTesla)', ...
	'Style','text', ...
	'Tag','StaticText1');
editB1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[206.5 155.25 108.25 16.5], ...
	'String','24.6', ...
	'Style','edit', ...
	'Tag','EditText1');
% end B1
% w
txtw = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[246.25 132.25 41.25 13.5], ...
	'String','w (MHz)', ...
	'Style','text', ...
	'Tag','StaticText1');
editw = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[236.5 115.25 58.25 16.5], ...
	'String','127.74', ...
	'Style','edit', ...
	'Tag','EditText1');
% end w
% Tp
txtTp = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[230.25 92.25 71.25 13.5], ...
	'String','Tp (miliseconds)', ...
	'Style','text', ...
	'Tag','StaticText1');
editTp = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[246.5 75.25 38.25 16.5], ...
	'String','1.5', ...
	'Style','edit', ...
	'Tag','EditText1');
% end Tp
% phase angle
txtphase = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[330.25 172.25 71.25 13.5], ...
	'String','RF Phase Angle', ...
	'Style','text', ...
	'Tag','StaticText1');
editphase = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[346.5 155.25 38.25 16.5], ...
	'String','0', ...
	'Style','edit', ...
	'Tag','EditText1');
% end phase anfle
% tilt angle
txttilt = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[330.25 132.25 71.25 13.5], ...
	'String','RF Tilt Angle', ...
	'Style','text', ...
	'Tag','StaticText1');
edittilt = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[346.5 115.25 38.25 16.5], ...
	'String','90', ...
	'Style','edit', ...
	'Tag','EditText1');
% end phase angle
%-------------------------Relaxation times---------------------
% T1
txtT1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[430.25 172.25 71.25 13.5], ...
	'String','T1 (ms)', ...
	'Style','text', ...
	'Tag','StaticText1');
editT1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[446.5 155.25 38.25 16.5], ...
	'String','1000', ...
	'Style','edit', ...
	'Tag','EditText1');
% end T1
% T2
txtT2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[430.25 132.25 71.25 13.5], ...
	'String','T2 (ms)', ...
	'Style','text', ...
	'Tag','StaticText1');
editT2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	    'Enable','on',...
	'ListboxTop',0, ...
	'Position',[446.5 115.25 38.25 16.5], ...
	'String','100', ...
	'Style','edit', ...
	'Tag','EditText1');
% end T2
